Cgarciag/pytest setup
Immutare/mlops-project-team13 pull request #18
Opened 2024-11-02 21:53 UTC by Immutare

Packaged the project to a maternalhealth project to allow the proper testing of the project as it should be separated, will probably break the .venv of the users.
Will handle issues when they arise.

2024-11-02 22:19 UTC, manuelurgell requested changes

2024-11-02 22:19 UTC, manuelurgell commented on requirements.txt
> +pywin32==306
No deberíamos quitar el `; platform_system == "Windows"`

2024-11-02 22:19 UTC, manuelurgell commented on src/maternalhealth/pyproject.toml
> +[tool.mypy]
Since we already have mypy settings, do you think we could add this to pre-commit config? https://github.com/pre-commit/mirrors-mypy

2024-11-02 22:20 UTC, manuelurgell commented on setup.cfg
> +max-line-length = 160
max-line-length = 79

2024-11-02 22:23 UTC, manuelurgell requested changes
Could we add a screenshot of the output for `pre-commit run --all-files`?

2024-11-02 22:35 UTC, Immutare commented on src/maternalhealth/pyproject.toml
> +[tool.mypy]
I'm still on the middle of developing  a hook to run the tests, also developing more tests right now

2024-11-02 22:35 UTC, Immutare commented on requirements.txt
> +pywin32==306
Will fix, give me a sec

2024-11-03 00:47 UTC, siegfriedgm approved these changes

2024-11-03 00:53 UTC, merged